### ISSUE TITLE
TypeError: cannot deepcopy this pattern object after importing galpy

### ISSUE THREAD

**Issue by webbjj** [jobovy/galpy#524]
## 🐛 Bug

Hi Jo - I installed the latest version of galpy, and the installation seemed to go fine. However as soon as I import galpy I seem to get an error related to copy. 

### Reproducible example

>>> from galpy import potential
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/webbjj/local/lib/python3.6/site-packages/galpy/__init__.py", line 12, in <module>
    from .util.config import (__config__, __orig__config__, configfilename,
  File "/home/webbjj/local/lib/python3.6/site-packages/galpy/util/__init__.py", line 10, in <module>
    from ..util.config import __config__
  File "/home/webbjj/local/lib/python3.6/site-packages/galpy/util/config.py", line 59, in <module>
    __orig__config__= copy.deepcopy(__config__)
  File "/usr/local/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/lib/python3.6/copy.py", line 161, in deepcopy
    y = copier(memo)
TypeError: cannot deepcopy this pattern object

You may want to try out your example on the galpy REPL, which always runs the latest version of the code, to make sure that the bug hasn't been resolved yet in the development version: https://www.galpy.org/repl -->

### Expected behavior

The expected behaviour is that potential is imported without error

### System Details

Linux-3.10.0-1160.24.1.el7.x86_64-x86_64-with-centos-7.9.2009-Core
Python 3.6.5 (default, May  9 2018, 16:41:12) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
numpy 1.19.5
scipy 1.5.4
matplotlib 3.3.4
astropy 4.1

Note - the import galpy command you suggest returns the same error as above

### Additional context

I also had to update setuptools when I installed the newest version of galpy, otherwise it wouldn't install. Also note this is on your server, not my laptop.

**Comment by jobovy** [comment]
Python 3.6 is no longer supported. Can you try with Python >=3.7?
